### ISSUE TITLE
feature request password login 

### ISSUE THREAD

**Issue by incomingflyingbrick** [aoudiamoncef/ubuntu-sshd#2]
Hi Can you add a feature that could allow user to login with a password and user name?

**Comment by aoudiamoncef** [comment]
Hi, it's already possible

https://github.com/aoudiamoncef/ubuntu-sshd/blob/main/configure-ssh-user.sh

**Comment by incomingflyingbrick** [comment]
Hi, I added some environment variable to the dockerfile provided using ENV directive, when I logged in using ssh, the environment variable is gone, but if i use docker exec -it <container_id> /bin/bash to log in the environment variable came back. This due to nature of sshd or the image's problem?

**Comment by aoudiamoncef** [comment]
The issue you're experiencing is due to the nature of how environment variables are handled when you log in via SSH. When you log in using `ssh`, a new session is created, and the environment variables set using the `ENV` directive in the Dockerfile are not automatically propagated to this new session. This behavior is different from when you use `docker exec -it <container_id> /bin/bash`, where the environment variables set in the Dockerfile are available because the `exec` command uses the environment of the running container.

To ensure that environment variables are available in your SSH session, you can add them to the user's shell profile. You can modify your Dockerfile and the `configure-ssh-user.sh` script to make it work.
